### ISSUE TITLE
when dynamicwallpaperconverter convert Catalina.heic has noises

### ISSUE THREAD

**Issue by spphinslove** [zzag/plasma5-wallpapers-dynamic#58] opened 2020-08-01 08:02 UTC
I use the python tool to convert Catalina.heic which file from macOS,and I use heif-convert to extra jpg(6016x6016).
the first image is wallpaper screenshot.the second is extra from origin heic file.
![图片](https://user-images.githubusercontent.com/11383988/89097268-0663f200-d410-11ea-9cde-5b8ba30653dc.png)
![图片](https://user-images.githubusercontent.com/11383988/89097273-124fb400-d410-11ea-9226-43d8c2ce292d.png)

**Comment by zzag** [comment] 2020-08-01 09:04
What is the resolution of your display? and does omitting "--crossfade" helps to get rid of the noise?

**Comment by zzag** [comment] 2020-08-01 09:11
Ideally, we need to specify the `sourceSize` so QtQuick can downscale the image the best it can, but it's not really an option right now due to the current QQuickImageProvider API limitations. With Qt 6, it will be possible to specify `sourceSize`, though.

**Comment by zzag** [comment] 2020-08-01 09:29
The first image looks crisp, while the second one looks more blurry, I wonder whether it is downscaled using mipmaps.

**Comment by spphinslove** [comment] 2020-08-04 09:11
> 
> 
> 显示器的分辨率是多少？ 省略“ --crossfade”是否有助于消除噪音？

I havent add --crossfade option

**Comment by spphinslove** [comment] 2020-08-04 09:17
> 
> 
> The first image looks crisp, while the second one looks more blurry, I wonder whether it is downscaled using mipmaps.

second image is 6016x6016,I just use heif-convert _imagename_.heic.and I think second image is normal.

**Comment by zzag** [comment] 2020-08-04 12:25
Hmm, I'm not sure that I understand what you are doing. Did you run heif-convert on both the original heic file and the heic file that the script had produced?

**Comment by zzag** [comment] 2020-08-04 20:30
I believe that the script doesn't introduce any noise. The problem is the way how the images are downscaled. If that's indeed the case, I don't know how to fix this bug before Qt 6 is released without sacrificing performance.

**Comment by spphinslove** [comment] 2020-08-05 02:20
> I believe that the script doesn't introduce any noise. The problem is the way how the images are downscaled. If that's indeed the case, I don't know how to fix this bug before Qt 6 is released without sacrificing performance.

Thank you,I think it's downscaled probelem,because I convert other heic(not form macOS) work fine.

**Closed** 2020-08-05 02:20 UTC

**Comment by zzag** [comment] 2020-08-05 04:50
Just to be sure, could you please test whether enabling mipmapping fixes the problem?

[0001-Use-mipmap-filtering.patch.txt](https://github.com/zzag/plasma5-wallpapers-dynamic/files/5026189/0001-Use-mipmap-filtering.patch.txt)
